spring:
  r2dbc:
    username: spring-template
    password: 123456
    url: r2dbc:postgresql://netuno:5432/spring_template
  jackson:
    locale: en_US
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: UTC
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
      FAIL_ON_UNKNOWN_PROPERTIES: false

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://authserver:8080
logging:
  level:
    org.springframework.r2dbc: debug

app:
  paging:
    maxItemsPerPage: 30
    defaultPageSize: 10
    defaultSortProperty: createdAt
  services:
    timeout: 10
    connectTimeout: 5
    account: http://localhost:3000
    oauthServer: http://netuno:8090
